services:
  tedge:
    build:
      dockerfile: images/tedge/Dockerfile
      context: .
      args:
        TEST_IMAGE: ${TEST_IMAGE:-ghcr.io/thin-edge/tedge-demo-main-systemd:latest}
    privileged: true
  simulator:
    build:
      dockerfile: images/simulator/Dockerfile
      context: .
    privileged: true
